print(40>30)
print(40<30)
print(40==30)
print(40!=30)
print(40>=30)
print(40<=30)
print("...............................")
print(True and True)
print(True and False)
print(False and True)
print(False and False)
print("...............................")
print(True or True)
print(True or False)
print(False or True)
print(False or False)
print(bool(0))
print(bool(-2))
print(bool(''))
print(bool("hello"))
